import type { Metadata } from 'next'
import { Vazirmatn } from 'next/font/google'
import './globals.css'
import Nav from '@/app/cmp/nav/nav'

const vazirmatn = Vazirmatn({
  variable: '--font-vazirmatn',
  subsets: ['arabic'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html dir={'rtl'} lang='fa'>
      <body className={`${vazirmatn.variable} antialiased`}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
